### ISSUE TITLE
`rustfmt` fails with "left behind trailing whitespace"

### ISSUE THREAD

**Issue by 617a7a** [planus-org/planus#167]
Not quite sure on the root cause of this, but with my current schema I'm getting an error from rustfmt when generating the code. This is on the latest commit.

[Download the FBS files](https://github.com/planus-org/planus/files/10427931/auth.zip)

```console
planus rust -o rs/src/gen.rs auth/auth.fbs
Error: 
   0: codegen error: rustfmt failed with exit code exit code: 1 and message:
      error[internal]: left behind trailing whitespace
          --> <stdin>:3400:3400:1
           |
      3400 |
           | ^^^^^^^^^^^^
           |

      warning: rustfmt has failed to format. See previous 1 errors.

   0:

Location:
   crates\planus-cli\src\app\rust.rs:27
```

**Comment by TethysSvensson** [comment]
So there are a few related problems here:

* Rustfmt cannot format that block
* Because rustfmt cannot format the block, it will leave trailing whitespace
* Rustfmt will then warn the user about the trailing that it was unable to remove.

I think we could get rid of the rustfmt warning by not emitting the trailing whitespace, but that seems a bit difficult to manage consistently, since it's difficult to consistently control the whitespace output by our askama templates.

I think a better solution is to run rustfmt twice:

* First a run with `max_width=1000000`, which should be able to format everything and thus remove any trailing whitespace.
* After that a run with the default setting for `max_width`, which will cause rustfmt to behave normally for most blocks. Any blocks it is unable to format, it will leave as-is which is not ideal but still good enough.

While we are at it, I think would should add an `--edition 2021` to the arguments for rustfmt.
